name: moula_manager
description: "A Flutter Projet presented by Sansus Mathys and Pariel-Abadie Florian"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/car.png
    - lib/images/food.jpg
    - lib/images/home.png
