name: moula_manager
description: "A Flutter Projet presented by Sansus Mathys and Pariel-Abadie Florian"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite: ^2.3.2  # Vérifie la dernière version sur pub.dev

flutter:
  uses-material-design: true
