name: moula_manager
description: "A Flutter Projet presented by Sansus Mathys and Pariel-Abadie Florian"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite: ^2.3.2  # Vérifie la dernière version sur pub.dev

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/images/car.png
    - lib/images/food.png
    - lib/images/housing.png
    - lib/images/other.png
